"""studentwork-artistwork

Revision ID: 0b1775781638
Revises: 3fc47c7a15bd
Create Date: 2024-09-01 00:22:40.729742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1775781638'
down_revision = '3fc47c7a15bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artistwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('descriptions', sa.String(length=2048), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_studentwork',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('studentwork_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['studentwork_id'], ['studentwork.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_studentwork')
    op.drop_table('artistwork')
    op.drop_table('studentwork')
    # ### end Alembic commands ###
