"""add fields show_on_homepage and homepage_photo in Course model

Revision ID: 1e110891469f
Revises: 3a3cb13c2407
Create Date: 2025-01-27 23:58:13.831069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e110891469f'
down_revision = '3a3cb13c2407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_on_homepage', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('homepage_photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('homepage_photo')
        batch_op.drop_column('show_on_homepage')

    # ### end Alembic commands ###
