"""add the field alt in model Video

Revision ID: 1ebef11ba4fa
Revises: 583fa6e2a244
Create Date: 2024-11-22 09:09:04.520706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebef11ba4fa'
down_revision = '583fa6e2a244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('alt')

    # ### end Alembic commands ###
