"""add field prifession in model Artist

Revision ID: 3150d24be2e6
Revises: 2b5f66e4b28f
Create Date: 2025-02-02 16:57:11.235014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3150d24be2e6'
down_revision = '2b5f66e4b28f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profession', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('profession')

    # ### end Alembic commands ###
