"""new field in models Payment and Lesson

Revision ID: 3a3cb13c2407
Revises: 1ebef11ba4fa
Create Date: 2025-01-10 00:10:18.235380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3cb13c2407'
down_revision = '1ebef11ba4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
