"""correct a model Course learning_process_description field

Revision ID: 4c3456f31680
Revises: 4cfe064929d1
Create Date: 2024-11-06 00:57:32.747577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c3456f31680'
down_revision = '4cfe064929d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_process_description', sa.Text(), nullable=True))
        batch_op.drop_column('learning_process_title_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_process_title_description', mysql.TEXT(), nullable=True))
        batch_op.drop_column('learning_process_description')

    # ### end Alembic commands ###
