"""add fields title en Course and mode fields

Revision ID: 4cfe064929d1
Revises: 5af3aec55234
Create Date: 2024-11-05 23:51:25.361509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cfe064929d1'
down_revision = '5af3aec55234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_process_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('learning_process_title_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('features_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('features_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('artist_title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('artist_photo_preview', sa.String(length=255), nullable=True))
        batch_op.drop_column('features')
        batch_op.drop_column('information')
        batch_op.drop_column('skills')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('information', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('features', mysql.TEXT(), nullable=True))
        batch_op.drop_column('artist_photo_preview')
        batch_op.drop_column('artist_title')
        batch_op.drop_column('skills_description')
        batch_op.drop_column('skills_title')
        batch_op.drop_column('features_description')
        batch_op.drop_column('features_title')
        batch_op.drop_column('learning_process_title_description')
        batch_op.drop_column('learning_process_title')

    # ### end Alembic commands ###
