"""delete field students_work

Revision ID: 52a64340a9ce
Revises: 745faf90be62
Create Date: 2024-11-01 00:01:38.400274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52a64340a9ce'
down_revision = '745faf90be62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('students_work')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('students_work', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
