"""edit fields Course: iimage,description,artist

Revision ID: 5af3aec55234
Revises: e05a4304cf83
Create Date: 2024-11-01 02:44:33.698272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5af3aec55234'
down_revision = 'e05a4304cf83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('preview_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('artist_description', sa.Text(), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('artist')
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('artist', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('artist_description')
        batch_op.drop_column('preview_photo')
        batch_op.drop_column('preview_description')

    # ### end Alembic commands ###
