"""Add new_field for course

Revision ID: 6b26d87d5737
Revises: 4a6d5d3abe19
Create Date: 2024-07-14 23:22:04.291473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b26d87d5737'
down_revision = '4a6d5d3abe19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('level', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('duration')
        batch_op.drop_column('level')
        batch_op.drop_column('image')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
