"""add field prpopular in model Course

Revision ID: 7848796eeaaf
Revises: 3150d24be2e6
Create Date: 2025-02-10 10:52:55.580344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7848796eeaaf'
down_revision = '3150d24be2e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popular', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('popular')

    # ### end Alembic commands ###
