"""Add new_field to Course

Revision ID: 970606ee5c84
Revises: 5be4210e66a3
Create Date: 2024-07-10 12:26:59.273294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '970606ee5c84'
down_revision = '5be4210e66a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('about_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('information', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('features', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('students_work', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('promo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('registration_form', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('registration_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('artist', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('artist_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('artist_work', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('price', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('final_registration_form', sa.String(length=255), nullable=True))
        batch_op.drop_column('description')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.alter_column('module_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.alter_column('module_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=2048), nullable=True))
        batch_op.drop_column('final_registration_form')
        batch_op.drop_column('price')
        batch_op.drop_column('artist_work')
        batch_op.drop_column('artist_photo')
        batch_op.drop_column('artist')
        batch_op.drop_column('registration_photo')
        batch_op.drop_column('registration_form')
        batch_op.drop_column('promo')
        batch_op.drop_column('students_work')
        batch_op.drop_column('skills')
        batch_op.drop_column('features')
        batch_op.drop_column('information')
        batch_op.drop_column('about_photo')
        batch_op.drop_column('about')

    # ### end Alembic commands ###
