"""description in the model ArtistWork

Revision ID: b67cb6e4f80f
Revises: 0b1775781638
Create Date: 2024-09-03 22:40:27.711081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b67cb6e4f80f'
down_revision = '0b1775781638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artistwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=2048), nullable=True))
        batch_op.drop_column('descriptions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artistwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptions', mysql.VARCHAR(length=2048), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
