"""codelete fields from Course and add photo at Tariff

Revision ID: cec14cccc96d
Revises: 4c3456f31680
Create Date: 2024-11-07 12:07:48.909925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cec14cccc96d'
down_revision = '4c3456f31680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('artist_work')
        batch_op.drop_column('final_registration_form')

    with op.batch_alter_table('tariff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariff', schema=None) as batch_op:
        batch_op.drop_column('photo')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_registration_form', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('artist_work', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
